module.exports.descriptors = [
    'Retro',
    'Pixelated',
    'Kingdom',
    'Cartoon',
    'Blocky',
    'Lost',
    'Pirate',
    'Haunted',
    'Cyberwave',
    'Stardust',
    'Lighthouse',
    'Odyssey',
    'Mirage',
    'Wildcard',
    'Aurora',
    'BubblePop',
    'HappyHive',
    'Jolly'
]

module.exports.tags = [
    'Guardians',
    'Empires',
    'Rebellion',
    'Souls',
    'Nations',
    'Crusaders',
    'Frontier',
    'Apocalypse',
    'Dominion',
    'Paradise',
    'Quest',
    'Adventure',
    'Escape',
    'Legacy',
    'Mystery',
    'Journey',
    'Mission',
    'Saga',
    'Conquest',
    'RPG',
    'Battlegrounds'
]

