name: env_tutorial
## Triggers the workflow on when there is a push, or 
## pull request on the main branch
on: [push] 

env:
  ## Sets environment variable
  TEST_SECRET: ${{ secrets.TEST_SECRET }}    

jobs:
  job1:
    ## The type of runner that the job will run on, 
    ## here it runs on ubuntu latest
    runs-on: ubuntu-latest 
    steps:
        - name: Git checkout
          uses: actions/checkout@v2

        - name: Use Node 12.x
          uses: actions/setup-node@v1
          with:
            node-version: 12.x

        - name: Install Dependencies (prod)
          run: yarn install --frozen-lockfile --production

        - name: Run Tests (JEST)
          run: yarn test --ci --silent --testPathIgnorePatterns=experimental
          env:
            TEST_SECRET: ${{ secrets.TEST_SECRET }}