name: Import Secret

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Import Secret
      env:
        TEST_SECRET: ${{ secrets.TEST_SECRET }}
    - name: Echo Secret
      run: echo $TEST_SECRET
